### ISSUE TITLE
Error when trying to use PackageManager to update itself

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/PackageManager#121] opened 2024-01-12 12:29 UTC
I just update to v1.4.3 and during the process I got:

~~~
Remove old version of packagemanager at /Users/jdm/Library/Preferences/GAP/pkg/PackageMa\
nager-1.4.2/ ? [y/N] y
Error, List Unbind: <list> must be a mutable list in
  Remove( dirname ); at /Users/jdm/gap/lib/files.gi:377 called from
RemoveDirectoryRecursively( dir
 ); at /Users/jdm/Library/Preferences/GAP/pkg/PackageManager-1.4.2/gap/PackageManager.gi\
:1217 called from
PKGMAN_RemoveDir( olddir
 ); at /Users/jdm/Library/Preferences/GAP/pkg/PackageManager-1.4.2/gap/PackageManager.gi\
:780 called from
<function "UpdatePackage">( <arguments> )
 called from read-eval loop at *stdin*:2
type 'quit;' to quit to outer loop
~~~

**Comment by james-d-mitchell** [comment] 2024-01-12 12:30
Also when updating `smallgrp`:

~~~
gap> UpdatePackage("smallgrp");
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/smallgrp/PackageInfo.g ...
#I  smallgrp version 1.5.3 will be installed, replacing 1.5
#I  Downloading archive from URL https://github.com/gap-packages/SmallGrp/releases/download/v1.5.3/SmallGrp-1.5.3.tar.gz ...
#I  Saved archive to /var/folders/q6/lfg29jgd05n7bshzrcsc58100000gq/T//gaptempdirZSOYz6/SmallGrp-1.5.3.tar.gz.pkgman
#I  Extracting to /Users/jdm/Library/Preferences/GAP/pkg/SmallGrp-1.5.3 ...
#I  Checking dependencies for SmallGrp...
#I    GAPDoc >= 1.5: true
#I  Running compilation script on /Users/jdm/Library/Preferences/GAP/pkg/SmallGrp-1.5.3 ...
#I  + GAPROOT=/Users/jdm/gap
+ PKGDIR=/Users/jdm/Library/Preferences/GAP/pkg/SmallGrp-1.5.3
+ command -v gmake
+ cd /Users/jdm/Library/Preferences/GAP/pkg/SmallGrp-1.5.3
+ '[' -x autogen.sh ']'
+ '[' -x configure ']'

#I  Checking dependencies for SmallGrp...
#I    GAPDoc >= 1.5: true
Remove old version of smallgrp at /Users/jdm/Library/Preferences/GAP/pkg/SmallGrp-1.5/ ?\
 [y/N] y
Error, List Unbind: <list> must be a mutable list in
  Remove( dirname ); at /Users/jdm/gap/lib/files.gi:377 called from
RemoveDirectoryRecursively( dir
 ); at /Users/jdm/Library/Preferences/GAP/pkg/PackageManager-1.4.3/gap/PackageManager.gi\
:1217 called from
PKGMAN_RemoveDir( olddir
 ); at /Users/jdm/Library/Preferences/GAP/pkg/PackageManager-1.4.3/gap/PackageManager.gi\
:780 called from
<function "UpdatePackage">( <arguments> )
 called from read-eval loop at *stdin*:3
type 'quit;' to quit to outer loop
brk>
~~~

**Comment by fingolfin** [comment] 2024-01-12 12:32
Which GAP versions? With 4.12.2 or with gap master?

**Comment by james-d-mitchell** [comment] 2024-01-12 12:32
Sorry GAP master

**Comment by fingolfin** [comment] 2024-01-12 12:33
I'd guess this is most like with GAP master, and the issue is in GAP, not in PackageManager. Specifically that line is one where I recently switched to using `Remove`... and it is fishy because it modifies the argument given to the function...

**Comment by fingolfin** [comment] 2024-01-12 13:42
Should be resolved by https://github.com/gap-system/gap/pull/5584

**Closed** 2024-01-14 19:17 UTC
